# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47a364df3904efd223c10461a171e477"
name = "SEO Implementor"
application_url = "https://seo-implementor.vercel.app"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://seo-implementor.vercel.app/auth/callback",
  "https://seo-implementor.vercel.app/auth/session-token"
]

[build]
automatically_update_urls_on_dev = true
